// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzNY7KQatMyRquUkn4u4NXe0Jx_3vdXlc',
    appId: '1:815358437444:web:c1916cba1d10e56f24b411',
    messagingSenderId: '815358437444',
    projectId: 'my-mobile-app-e62f5',
    authDomain: 'my-mobile-app-e62f5.firebaseapp.com',
    storageBucket: 'my-mobile-app-e62f5.firebasestorage.app',
    measurementId: 'G-P08QPNTNW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp7GBWsF0eSu7gI6HSypnAVchm0yUS8LM',
    appId: '1:815358437444:android:e2e4594d26a8ef5424b411',
    messagingSenderId: '815358437444',
    projectId: 'my-mobile-app-e62f5',
    storageBucket: 'my-mobile-app-e62f5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdBpqThy7SL6cSdpq2fl8M06usztI4ZdU',
    appId: '1:815358437444:ios:be11db9134b3437924b411',
    messagingSenderId: '815358437444',
    projectId: 'my-mobile-app-e62f5',
    storageBucket: 'my-mobile-app-e62f5.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl2sQ9pkDTJwNHK5zHTqLAta-QI_hoyKA',
    appId: '1:914116713401:ios:bfeede2a8b714c06f5f468',
    messagingSenderId: '914116713401',
    projectId: 'my-mobile-app-4865b',
    storageBucket: 'my-mobile-app-4865b.firebasestorage.app',
    iosClientId: '914116713401-dbv2ad1uu5tfj4ut9qon3bl9ekfqu2er.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuPLC0WDwag9VYzNnblvtCvrG1GqjQD_E',
    appId: '1:914116713401:web:fcf41835f9b90d0af5f468',
    messagingSenderId: '914116713401',
    projectId: 'my-mobile-app-4865b',
    authDomain: 'my-mobile-app-4865b.firebaseapp.com',
    storageBucket: 'my-mobile-app-4865b.firebasestorage.app',
    measurementId: 'G-93QTXKRV24',
  );
}
